backend:
  name: git-gateway
  branch: main

media_folder: "docs/image"
public_folder: "/images"

collections:
  - name: "getting-started"
    label: "Getting Started"
    folder: "docs/getting-started"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Body", name: "body", widget: "markdown"}
